server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:sqlserver://sprint4.database.windows.net:1433;database=sprint4;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: adminsprint4
    password: Fiap2TDSPY2025

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true
    show-sql: true
