server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always
  forward-headers-strategy: native # Adicionado para funcionar bem com o Nginx da VPS

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/portfolio_mottu_db
    username: portfolio_lucasalmeida
    password: Lucas2002--

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  flyway:
    enabled: false  # DESLIGADO PARA SEMPRE
    jpa:
      hibernate:
        ddl-auto: update # Apenas atualiza se você mudar uma entidade, não recria nada
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false # Evita consulta de sistema que dá erro de permissão